trader:
  broker:
    paytm:
      baseUrl: https://developer.paytmmoney.com/
      auth:
        apiKey: 6d2a56063b4041138bfa791104e1bd89
        apiSecret: 5c484dfde00b4b248c29faacaea28248

spring:
  profiles:
    active: mock

# H2 Database
  h2:
    console:
      enabled: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect